### ISSUE TITLE
Not using Theme metadata when generating themes

### ISSUE THREAD

**Issue by BickelLukas** [DevExpress/devextreme-cli#59]
I have an Angular Project and to generate the theme I am using the following metadata.json file 

``` json 
{
    "items": [
        {
            "key": "@base-accent",
            "value": "#ffe200"
        }
    ],
    "baseTheme": "material.blue.light",
    "outputColorScheme": "base",
    "makeSwatch": false,
    "assetsBasePath": "../../../node_modules/devextreme/dist/css/"
}
```

This file was exported by the ThemeBuilder UI. When I then use the cli to generate the css and vars scss file the custom "@base-accent" color is not used. 

For example in the variables.scss file it says
``` scss
...
$base-accent: #03A9F4;

```

my devextreme.json file looks like this.
``` json
{
    "applicationEngine": "angular",
    "build": {
        "commands": [
            {
                "command": "build-theme",
                "options": {
                    "inputFile": "src/themes/metadata.json",
                    "outputFile": "src/themes/generated/theme.css"
                }
            },
            {
                "command": "export-theme-vars",
                "options": {
                    "inputFile": "src/themes/metadata.json",
                    "outputFile": "src/themes/generated/variables.scss"
                }
            }
        ]
    }
}

```

**Comment by dxvladislavvolkov** [comment]
Fixed in [PR](https://github.com/DevExpress/DevExtreme/pull/6534)

**Comment by cfsean** [comment]
@dxvladislavvolkov  I don't think this should have been closed. I still experience this exact issue. 

I have manually included devextreme-theme-builder V18.2.5 in my project and it still doesn't work.

**Comment by babich-a** [comment]
Hi, @cfsean. I get `$base-accent: #ffe200;` in variables.scss when run `devextreme build` with the described `src/themes/meatadata.json` and `devextreme.json`. Could you give more details?

**Comment by cfsean** [comment]
The issue was with a package dependency somewhere. 

After I deleted my yarn.lock file and resolved all packages again, the problem has been resolved. Somewhere, you have a package dependency that is not set to the correct minimum version. I checked and I was using devextreme 18.2.5, less 3.9.0, devextreme-cli 1.0.2 and devextreme-thembuilder 18.2.5. I don't know what other dependencies of these projects may have been causing the issue. Unfortunately I don't have time to investigate it any further. 

You may like to start by updating the dependency in this project for devextreme-themebuilder from 18.2.4 to 18.2.5 though.
